version: '3.8'

services:

  msproducto:
    build:
      context: ./ms_producto
      dockerfile: Dockerfile
    ports:
      - "8060:8080"
    depends_on:
      - dbProductos
    environment:
      - ConnectionStrings__DefaultConnection=Server=dbProductos,1433;Database=DB_productos;User Id=sa;Password=Jhonatan.Espinoza.2025;TrustServerCertificate=True;
  dbProductos:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Jhonatan.Espinoza.2025
    ports:
      - "1438:1433"
    volumes:
      - dbProductosData:/var/opt/mssql

  mstransaccion:
    build:
      context: ./ms_transaccion
      dockerfile: Dockerfile
    ports:
      - "8061:8080"
    depends_on:
      - dbTransacciones
    environment:
      - ConnectionStrings__DefaultConnection=Server=dbTransacciones,1433;Database=DB_transaccion;User Id=sa;Password=Jhonatan.Espinoza.2025;TrustServerCertificate=True;
      - ApisExternas__Productos=http://msproducto:8080


  dbTransacciones:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Jhonatan.Espinoza.2025
    ports:
      - "1439:1433"
    volumes:
      - dbTransaccionData:/var/opt/mssql
  webgestionproducto:
    build:
      context: ./web_gestion_productos
      dockerfile: Dockerfile
    ports:
      - "8062:80"
    depends_on:
      - msproducto
      - mstransaccion
    volumes:
      - ./dist:/usr/share/nginx/html
volumes:
    dbProductosData:
    dbTransaccionData:
     